export default {
    "FELONY_CLASS_A": "FELONY_CLASS_A",
    "FELONY_CLASS_B": "FELONY_CLASS_B",
    "FELONY_CLASS_C": "FELONY_CLASS_C",
    "MISDEMEANOR": "MISDEMEANOR",
    "GROSS MISDEMEANOR": "GROSS MISDEMEANOR"
};